apiVersion: v1
kind: Service
metadata:
  name: aks-storage-service
  namespace: storage
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: aks-storage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000