apiVersion: v1
kind: Service
metadata:
  name: aks-sql-service
  namespace: sql
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: aks-sql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5050