apiVersion: v1
kind: Service
metadata:
  name: aks-api-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: aks-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080