apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-storage-deployment
  namespace: storage
  labels:
    app: aks-storage    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-storage
  template:
    metadata:
      labels:
        app: aks-storage
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: workload-identity-storage 
      containers:
        - name: aks-storage
          image: jfvacr.azurecr.io/wi-storage-image:remote-v2 # Update with your ACR login server and image tag
          ports:
            - containerPort: 5000         
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"