apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 6e9a1bdf-8bcc-4c3a-b827-1323cc7dbe38
  labels:
    azure.workload.identity/use: "true"
  name: workload-identity-storage
  namespace: storage
