apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 5766ef1f-1b5a-44ee-a256-05a60d7cc42e
  labels:
    azure.workload.identity/use: "true"
  name: workload-identity-storage
  namespace: storage
